version: '3.8'

services:
  app:
    build: .
    container_name: nafidha_ai
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://db:27017
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_VISION_MODEL=qwen3.5:4b
      - OLLAMA_TEXT_MODEL=aya:8b
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./reg_uploads:/app/reg_uploads
    depends_on:
      - db
      - ollama
    restart: always

  db:
    image: mongo:latest
    container_name: nafidha_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always

  ollama-pull-models:
    image: curlimages/curl:latest
    container_name: ollama_puller
    depends_on:
      - ollama
    entrypoint: /bin/sh
    command: >
      -c "sleep 5; 
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"qwen3.5:4b\"}';
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"aya:8b\"}';"

volumes:
  mongo_data:
  ollama_data: